### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tml94** [dcernst/T-Avoiding#10]
Since we are claiming in the hard case that \sigma is not fully commutative, do we need to have a case showing that sigma being fully commutative has Property T?

**Comment by tml94** [comment]
Maybe not upon further inspection I think FC elements have to be in the easy case because of the way in which they are set up... There aren't any braids so if they will fall into the easy case since there will be a block in the second column that is not blocked top and bottom in the first column.

**Comment by tml94** [comment]
Never mind. I have finally fully figured out what I am supposed to be typing and realized that I am being silly. Being not FC in the implies that this hard case exists and I can go from there... I hadn't finished the claim statement in the hard case so I was clearly not sure what I was supposed to be proving and now I have figured it all out (theoretically) until I forget again...

**Comment by dcernst** [comment]
So, are we good here?

**Comment by tml94** [comment]
Yeah. It helps when you have the whole statement written that you are trying to prove. But yes we are good.
