### ISSUE TITLE
Section 2.2 

### ISSUE THREAD

**Issue by tml94** [dcernst/T-Avoiding#2]
Just for general knowledge and to help me understand the way the paper is defining equivalence classes in regards to commutation classes. It defines = (but squiggly) as by taking the reflexive transitive closure of ~ which we have defined as the relation between words (w'~w if they differ by a single commutation). 

The definition I found for reflexive transitive closure is here
Given R is a relation, reflexive transitive closure of R is the smallest relation S on A such that
R⊆S;
S is reflexive; and
S is transitive.

In the context is this extending ~ so that things that differ by multiple commutations are in the same commutation class. For example in A_3 the element 13231=13213=31231=31213. They are all in the same commutation class but 13231 and 31213 differ by two commutations?

**Comment by dcernst** [comment]
Yes, that's exactly right.

For this question and others you ask, once you are satisfied with the answer, I suggest "closing" this issue.  It will still be viewable later, but won't be listed as outstanding.
