### ISSUE TITLE
Retool heap examples to type A

### ISSUE THREAD

**Issue by dcernst** [dcernst/T-Avoiding#4]
At least temporarily, let's stick with examples in type A.

**Comment by tml94** [comment]
Changed the heap to s_2 s_1 s_3 s_2 so it is an FC heap. Don't know if this is helpful for you in the reconstructing of the heap picturs.

**Comment by tml94** [comment]
I have retooled this section now using that heap. I think that the examples I used as subheaps of the expression I used work as saturated subheaps and convex heaps but we should probably check this.

**Comment by dcernst** [comment]
We need to put new code in and turn "sideways".

**Comment by tml94** [comment]
Done!
